import { spawn } from "node:child_process";
import ffmpegStatic from "ffmpeg-static";
import { isSafeFfmpegInput } from "@/lib/ffmpeg-security";
const TEXT_CODECS=new Set(["subrip","srt","ass","ssa","webvtt","mov_text","text"]);
const NAMES:Record<string,string>={en:"English",eng:"English",fil:"Filipino",tl:"Filipino",tgl:"Filipino",es:"Spanish",spa:"Spanish",fr:"French",fra:"French",fre:"French",de:"German",deu:"German",ger:"German",it:"Italian",ita:"Italian",pt:"Portuguese",por:"Portuguese",ja:"Japanese",jpn:"Japanese",ko:"Korean",kor:"Korean",zh:"Chinese",zho:"Chinese",chi:"Chinese",ar:"Arabic",ara:"Arabic",hi:"Hindi",hin:"Hindi",th:"Thai",tha:"Thai",vi:"Vietnamese",vie:"Vietnamese",id:"Indonesian",ind:"Indonesian",ms:"Malay",msa:"Malay",may:"Malay",ru:"Russian",rus:"Russian",uk:"Ukrainian",tur:"Turkish",tr:"Turkish",und:"Unknown language"};
export interface EmbeddedSubtitle{streamIndex:number;lang:string;label:string;codec:string}
const executable=process.env.FFMPEG_PATH||ffmpegStatic||"ffmpeg";
function run(args:string[],capture=false):Promise<{stdout:Buffer;stderr:string}>{return new Promise((resolve,reject)=>{const child=spawn(executable,args,{stdio:["ignore","pipe","pipe"]}),chunks:Buffer[]=[];let stderr="";if(capture)child.stdout.on("data",(chunk:Buffer)=>chunks.push(chunk));else child.stdout.resume();child.stderr.setEncoding("utf8");child.stderr.on("data",(chunk:string)=>stderr+=chunk);child.on("error",reject);child.on("close",()=>resolve({stdout:Buffer.concat(chunks),stderr}));});}
export async function listEmbeddedSubtitles(filePath:string):Promise<EmbeddedSubtitle[]>{if(!isSafeFfmpegInput(filePath))return[];const{stderr}=await run(["-hide_banner","-i",filePath]),tracks:EmbeddedSubtitle[]=[];for(const line of stderr.split(/\r?\n/)){const match=line.match(/Stream #0:(\d+)(?:\(([^)]+)\))?.*Subtitle:\s*([^,\s]+)/i);if(!match)continue;const codec=match[3].toLowerCase();if(!TEXT_CODECS.has(codec))continue;const lang=(match[2]||"und").toLowerCase().split("-")[0];tracks.push({streamIndex:Number(match[1]),lang:lang==="und"?"":lang,label:NAMES[lang]||lang.toUpperCase(),codec});}return tracks;}
export async function extractEmbeddedSubtitle(filePath:string,streamIndex:number):Promise<Buffer|null>{if(!isSafeFfmpegInput(filePath)||!Number.isInteger(streamIndex)||streamIndex<0)return null;const tracks=await listEmbeddedSubtitles(filePath);if(!tracks.some(track=>track.streamIndex===streamIndex))return null;const{stdout}=await run(["-v","error","-i",filePath,"-map",`0:${streamIndex}`,"-f","webvtt","pipe:1"],true);return stdout.length?stdout:null;}
