"use client";

import { useEffect, useMemo, useState } from "react";
import { Check, CheckCircle2, Copy, Gift, Loader2, LockKeyhole, ShieldCheck, Sparkles, Upload } from "lucide-react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Plan={id:string;name:string;durationHours:number|null;isLifetime:boolean;price:number;finalPrice:number;percentOff:number};
type Method={id:string;name:string;accountName:string|null;accountNumber:string;iconUrl:string|null;qrUrl:string|null};
type Quote={originalPrice:number;amount:number;totalDiscount:number;percentOff:number;promoApplied:boolean;forcedPlanId:string|null;plan:Plan};

export default function RegistrationPayment(){
  const router=useRouter();
  const [token,setToken]=useState(""); const [plans,setPlans]=useState<Plan[]>([]); const [methods,setMethods]=useState<Method[]>([]);
  const [planId,setPlanId]=useState(""); const [promo,setPromo]=useState(""); const [quote,setQuote]=useState<Quote|null>(null); const [methodId,setMethodId]=useState("");
  const [senderName,setSenderName]=useState(""); const [senderAccountNumber,setSenderAccountNumber]=useState(""); const [referenceNumber,setReferenceNumber]=useState(""); const [receiptPath,setReceiptPath]=useState("");
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [copied,setCopied]=useState(false);

  // Initial checkout state is loaded from the browser session after hydration.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{const signupToken=sessionStorage.getItem("movieflix_signup_token")||"";if(!signupToken){router.replace("/register");return;}setToken(signupToken);Promise.all([fetch("/api/plans",{cache:"no-store"}).then(r=>r.json()),fetch("/api/payment-methods",{cache:"no-store"}).then(r=>r.json())]).then(([p,m])=>{if(p.success){const available=p.data.plans.slice(0,5);setPlans(available);setPlanId(available[0]?.id||"");}if(m.success){setMethods(m.data.methods);setMethodId(m.data.methods[0]?.id||"");}}).catch(()=>setError("Could not load checkout options."));},[router]);

  async function getQuote(code=promo,selectedPlan=planId){if(!selectedPlan||!token)return;setBusy(true);setError("");try{const response=await fetch("/api/register/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"quote",signupToken:token,planId:selectedPlan,promoCode:code})});const data=await response.json();if(!data.success)throw new Error(data.error);setQuote(data.data);if(data.data.forcedPlanId)setPlanId(data.data.forcedPlanId);}catch(e){setQuote(null);setError(e instanceof Error?e.message:"Code validation failed");}finally{setBusy(false);}}
  // The server always recomputes the base quote when the selected plan changes.
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(()=>{if(token&&planId)getQuote("",planId);},[token,planId]);

  async function uploadReceipt(file?:File){if(!file)return;setBusy(true);setError("");const body=new FormData();body.append("file",file);body.append("signupToken",token);try{const response=await fetch("/api/upload",{method:"POST",body});const data=await response.json();if(!data.success)throw new Error(data.error);setReceiptPath(decodeURIComponent(data.data.url.split("file=")[1]||""));}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setBusy(false);}}
  async function copy(value:string){let ok=false;try{await navigator.clipboard.writeText(value);ok=true;}catch{const field=document.createElement("textarea");field.value=value;field.style.position="fixed";field.style.opacity="0";document.body.appendChild(field);field.select();ok=document.execCommand("copy");field.remove();}setCopied(ok);window.setTimeout(()=>setCopied(false),1500);}
  async function submit(){if(!quote)return;setBusy(true);setError("");try{const response=await fetch("/api/register/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({signupToken:token,planId,promoCode:promo,paymentMethodId:methodId,senderName,senderAccountNumber,referenceNumber,receiptPath})});const data=await response.json();if(!data.success)throw new Error(data.error);sessionStorage.removeItem("movieflix_signup_token");router.replace("/login?registered=1");}catch(e){setError(e instanceof Error?e.message:"Checkout failed");}finally{setBusy(false);}}

  const selected=useMemo(()=>methods.find(m=>m.id===methodId),[methods,methodId]); const free=quote?.amount===0;
  return <main className="cinematic-bg min-h-screen px-3 py-5 text-white sm:px-6 sm:py-10"><div className="mx-auto max-w-6xl">
    <header className="mb-6 flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-300">MovieFlix membership</p><h1 className="mt-1 text-2xl font-black sm:text-4xl">Choose how you want to watch</h1><p className="mt-2 text-sm text-slate-400">Secure checkout · Up to five plans · Admin-verified payments</p></div><div className="hidden items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-xs font-bold text-emerald-300 sm:flex"><ShieldCheck className="h-4 w-4"/>Protected checkout</div></header>
    <div className="grid items-start gap-5 lg:grid-cols-[1fr_360px]">
      <div className="space-y-5">
        <section className="rounded-3xl border border-white/10 bg-[#0b1629]/95 p-4 sm:p-6"><Step number="1" title="Select a plan"/><div className="mt-4 flex snap-x gap-3 overflow-x-auto pb-2">{plans.map((p)=><button type="button" key={p.id} onClick={()=>{setPromo("");setPlanId(p.id);}} className={`relative min-w-[72vw] snap-start rounded-2xl border p-4 text-left transition sm:min-w-52 lg:min-w-0 lg:flex-1 ${planId===p.id?"border-cyan-300 bg-cyan-300/10 shadow-[0_0_24px_rgba(0,210,245,.13)]":"border-white/10 bg-white/5 hover:border-white/25"}`}>{planId===p.id&&<CheckCircle2 className="absolute right-3 top-3 h-5 w-5 text-cyan-300"/>}{p.percentOff>0&&<span className="rounded-full bg-orange-500 px-2 py-1 text-[10px] font-black">{p.percentOff}% OFF</span>}<h2 className="mt-3 text-lg font-black">{p.name}</h2><p className="mt-1 text-xs text-slate-400">{p.isLifetime?"Lifetime access":`${p.durationHours} hours access`}</p><div className="mt-5">{p.percentOff>0&&<span className="mr-2 text-xs text-slate-500 line-through">₱{p.price.toFixed(2)}</span>}<strong className="text-2xl text-cyan-300">₱{p.finalPrice.toFixed(2)}</strong></div></button>)}</div></section>
        <section className="rounded-3xl border border-white/10 bg-[#0b1629]/95 p-4 sm:p-6"><Step number="2" title="Promo or redeem code"/><div className="mt-4 flex gap-2"><div className="relative flex-1"><Gift className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-orange-300"/><Input value={promo} onChange={e=>setPromo(e.target.value.toUpperCase())} placeholder="ENTER CODE" className="h-12 pl-10 font-mono uppercase"/></div><Button onClick={()=>getQuote()} disabled={busy||!promo.trim()} className="btn-brand h-12 px-5">Apply</Button></div>{quote?.promoApplied&&<p className="mt-3 flex items-center gap-2 text-sm font-bold text-emerald-300"><Sparkles className="h-4 w-4"/>Code applied successfully</p>}</section>
        {!free&&<section className="rounded-3xl border border-white/10 bg-[#0b1629]/95 p-4 sm:p-6"><Step number="3" title="Payment method"/>{methods.length===0?<p className="mt-4 text-sm text-amber-300">No payment method is currently available.</p>:<><div className="mt-4 flex snap-x gap-3 overflow-x-auto pb-2">{methods.map(m=><button type="button" key={m.id} onClick={()=>setMethodId(m.id)} className={`flex min-w-40 snap-start items-center gap-3 rounded-2xl border p-3 text-left ${methodId===m.id?"border-cyan-300 bg-cyan-300/10":"border-white/10 bg-white/5"}`}>{m.iconUrl?<img src={m.iconUrl} alt="" className="h-10 w-10 rounded-xl bg-white object-contain"/>:<span className="flex h-10 w-10 items-center justify-center rounded-xl bg-cyan-300 font-black text-slate-950">{m.name[0]}</span>}<b className="text-sm">{m.name}</b></button>)}</div>{selected&&<div className="mt-4 grid gap-4 md:grid-cols-[1fr_150px]"><div><p className="text-xs text-slate-400">Send payment to</p><p className="mt-1 font-bold">{selected.accountName||selected.name}</p><div className="mt-2 flex items-center justify-between rounded-xl bg-black/25 p-3"><b className="font-mono text-cyan-200">{selected.accountNumber}</b><button type="button" onClick={()=>copy(selected.accountNumber)} aria-label="Copy account number" className="rounded-lg p-2 text-cyan-300 hover:bg-white/10">{copied?<Check className="h-5 w-5"/>:<Copy className="h-5 w-5"/>}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Input value={senderName} onChange={e=>setSenderName(e.target.value)} placeholder="Sender name"/><Input value={senderAccountNumber} onChange={e=>setSenderAccountNumber(e.target.value)} placeholder="Sender account number"/><Input value={referenceNumber} onChange={e=>setReferenceNumber(e.target.value)} placeholder="Reference number"/><label className="flex min-h-10 cursor-pointer items-center justify-center rounded-xl border border-white/15 px-3 text-sm font-bold hover:bg-white/5"><Upload className="mr-2 h-4 w-4"/>{receiptPath?"Receipt attached":"Attach receipt"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>uploadReceipt(e.target.files?.[0])}/></label></div></div>{selected.qrUrl&&<img src={selected.qrUrl} alt={`${selected.name} payment QR`} className="mx-auto aspect-square w-36 rounded-xl bg-white object-contain p-1"/>}</div>}</>}</section>}
      </div>
      <aside className="sticky top-4 rounded-3xl border border-cyan-300/15 bg-[#091426] p-5 shadow-2xl"><h2 className="text-lg font-black">Order summary</h2><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between text-slate-400"><span>Plan</span><b className="text-white">{quote?.plan?.name||plans.find(p=>p.id===planId)?.name||"—"}</b></div><div className="flex justify-between text-slate-400"><span>Original price</span><span>₱{(quote?.originalPrice||0).toFixed(2)}</span></div>{Boolean(quote?.totalDiscount)&&<div className="flex justify-between text-emerald-300"><span>Discount</span><span>−₱{quote!.totalDiscount.toFixed(2)}</span></div>}<div className="border-t border-white/10 pt-4"><div className="flex items-end justify-between"><span className="font-bold">Total due</span><strong className="text-3xl text-cyan-300">₱{(quote?.amount||0).toFixed(2)}</strong></div></div></div>{free&&<p className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-xs leading-5 text-emerald-200">Your valid code covers the full amount. No payment details are required.</p>}{error&&<p role="alert" className="mt-4 rounded-xl border border-red-400/25 bg-red-950/40 p-3 text-sm text-red-200">{error}</p>}<Button onClick={submit} disabled={busy||!quote||(!free&&(!methodId||!senderName||!senderAccountNumber||!referenceNumber||!receiptPath))} className="btn-brand mt-5 h-13 w-full text-sm font-black">{busy?<Loader2 className="mr-2 h-4 w-4 animate-spin"/>:<LockKeyhole className="mr-2 h-4 w-4"/>}{free?"Activate membership":"Submit secure payment"}</Button><p className="mt-3 text-center text-[11px] leading-4 text-slate-500">The server recalculates your price and validates your plan, code, payment method, and receipt before accepting checkout.</p></aside>
    </div>
  </div></main>;
}
function Step({number,title}:{number:string;title:string}){return <div className="flex items-center gap-3"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-cyan-300 text-xs font-black text-slate-950">{number}</span><h2 className="text-lg font-black">{title}</h2></div>}
