#!/usr/bin/env bash
# =============================================================================
#  MovieFlix Docker Installer — two modes, both via Docker Compose
#
#  1) UPDATE ONLY  — pull the latest code, rebuild the image, restart the app.
#                    Keeps ./data (database, thumbnails, uploads) and .env.
#
#  2) COMPLETE WIPEOUT — FRESH INSTALLATION. Stops and removes every container,
#                    deletes the database + all user data, wipes Redis, resets
#                    the repo to origin/main and regenerates .env with brand-new
#                    secrets. ANY local source changes are discarded.
#                    *** DESTRUCTIVE — you must type YES to confirm. ***
#
#  Run from the project root (where docker-compose.yml lives):
#      chmod +x install.sh && ./install.sh
# =============================================================================

set -euo pipefail

# ----------------------------- helpers --------------------------------------

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}   $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

gen_secret() {
  # 48 hex chars (>= the 32 char minimum enforced by the app)
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# --------------------------- prerequisite checks ----------------------------

req_check() {
  command -v docker >/dev/null 2>&1 || die "Docker is not installed or not in PATH."
  docker info >/dev/null 2>&1 || die "Docker daemon is not running (is the service started?)."

  if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
  else
    die "Docker Compose (v2) is not installed. Install the compose plugin, e.g.:\n  sudo apt install docker-compose-plugin"
  fi
  info "Using: $DC"

  command -v git >/dev/null 2>&1 || die "git is not installed."
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "Not a git repository. Run this script from the MovieFlix project root."
  [ -f docker-compose.yml ] || die "docker-compose.yml not found. Run this script from the MovieFlix project root."
}

swap_check() {
  # The Next.js production build needs ~3GB of ram+swap. On the low-RAM host,
  # building without a swapfile stalls the machine (see Dockerfile header).
  local ram_mb swap_mb total_gb
  ram_mb=$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 0)
  swap_mb=$(awk '/SwapTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 0)
  total_gb=$(( (ram_mb + swap_mb) / 1024 ))

  if [ "$total_gb" -lt 3 ]; then
    warn "Host has only ~${total_gb}GB of ram+swap (Ram: ${ram_mb}MB, Swap: ${swap_mb}MB)."
    warn "The Docker build may run out of memory and freeze the server."
    warn "Add a swapfile before proceeding, e.g.:"
    warn "  sudo fallocate -l 6G /swapfile && sudo chmod 600 /swapfile"
    warn "  sudo mkswap /swapfile && sudo swapon /swapfile"
    read -rp "Continue anyway? (y/N) " -n1 yn
    echo
    [ "$yn" = "y" ] || [ "$yn" = "Y" ] || die "Aborted. Free up ram/swap and try again."
  fi
}

# ----------------------------- .env handling --------------------------------

write_env_template() {
  # Regenerates .env from scratch (used by the WIPEOUT mode).
  local jwt_s jwt_r
  jwt_s=$(gen_secret)
  jwt_r=$(gen_secret)
  cat > .env <<EOF
# ===========================================
# MovieFlix — generated by install.sh (${1:-mode})
# ===========================================

# JWT secrets — REQUIRED, at least 32 chars (auto-generated)
JWT_SECRET=${jwt_s}
JWT_REFRESH_SECRET=${jwt_r}

# Public URL of the app (used in email links). Update to your real address.
# e.g. http://SERVER_IP:9000  or  https://movieflix.example.com
APP_PUBLIC_URL=http://localhost:9000

# TMDB metadata (optional). Free key: https://www.themoviedb.org/settings/api
TMDB_API_KEY=
TMDB_BASE_URL=https://api.themoviedb.org/3
TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p/

# SMTP so emails actually deliver (welcome, password reset, broadcast…).
# Without this the app still runs, but no emails are sent.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=MovieFlix <movieflix.support@gmail.com>

# Optional: restrict sessions to the same /24 subnet (0 = off, 1 = on)
SESSION_STRICT_SUBNET=0

# Host paths of your movie & series libraries (mapped into the container at
# /media/movies and /media/series). Set these to your real folders, e.g.:
#   MEDIA_MOVIES_HOST=/mnt/media/Media/MOVIES
#   MEDIA_SERIES_HOST=/mnt/media/Media/TV
# They live in .env on purpose: git pull / install.sh updates will NOT overwrite them.
MEDIA_MOVIES_HOST=/media/movies
MEDIA_SERIES_HOST=/media/series
EOF
  chmod 600 .env
}

ensure_env() {
  # UPDATE mode keeps the existing .env; only generates one if absent.
  if [ ! -f .env ]; then
    warn ".env not found — generating one with fresh secrets."
    write_env_template update
    warn "Edit .env to set APP_PUBLIC_URL, TMDB_API_KEY and SMTP_* before first launch."
  else
    ok "Reusing existing .env (secret JWT values are preserved)."
  fi
}

reset_env() {
  write_env_template wipeout
  ok "Generated a fresh .env with brand-new JWT secrets."
  warn "Edit .env now if you want: APP_PUBLIC_URL, TMDB_API_KEY, SMTP_*."
}

# ----------------------------- install modes --------------------------------

do_update() {
  info "Pulling the latest code from origin/main (ff-only, safe)."
  git fetch origin
  git pull --ff-only origin main

  swap_check
  ensure_env

  info "Rebuilding the Docker image (this takes a while on low-RAM hosts)."
  $DC build

  info "Starting / restarting the stack."
  $DC up -d --force-recreate

  ok "Update complete. Containers:"
  $DC ps
}

do_wipeout() {
  local answer
  echo
  warn "You are about to do a COMPLETE WIPEOUT — FRESH INSTALLATION."
  warn "This will:"
  warn "  - Stop & remove the running containers and the Redis volume"
  warn "  - DELETE ./data (database.sqlite, all accounts, thumbnails, uploads)"
  warn "  - Discard any local source changes and reset the repo to origin/main"
  warn "  - Regenerate .env with brand-new JWT secrets"
  echo
  read -rp "Type YES (uppercase) to continue: " answer
  [ "$answer" = "YES" ] || die "Wipeout cancelled."
  echo

  info "Stopping the stack and removing all containers/volumes."
  $DC down -v --remove-orphans 2>/dev/null || true

  info "Removing the app image (forces a clean rebuild)."
  docker rmi -f movieflix-app 2>/dev/null || true

  info "Deleting ./data (database + user data)."
  # The app container runs as root, so ./data contains root-owned files that a
  # plain `rm` as your user cannot remove ("Permission denied"). Delete through
  # a throwaway container instead — it runs as root and can wipe everything.
  if docker run --rm -v "$PWD":/work redis:7-alpine rm -rf /work/data 2>/dev/null; then
    ok "Data directory removed."
  elif docker run --rm -v "$PWD":/work alpine rm -rf /work/data 2>/dev/null; then
    ok "Data directory removed (using alpine)."
  else
    warn "Container-based removal failed. Falling back to sudo."
    sudo rm -rf ./data || die "Could not remove ./data: Permission denied. Fix manually, then re-run:\n  sudo chown -R \$(id -u):\$(id -g) ./data && sudo rm -rf ./data"
    ok "Data directory removed (via sudo)."
  fi

  info "Resetting the repository to origin/main (fresh source)."
  git fetch origin main
  git reset --hard origin/main
  git clean -fd --exclude=.env 2>/dev/null || true

  swap_check
  reset_env

  info "Building the fresh image (this takes a while on low-RAM hosts)."
  $DC build

  info "Starting the stack."
  $DC up -d

  ok "Fresh install complete!"
  echo
  echo "  Default admin login:  admin  /  admin123"
  echo "  Change it immediately after the first login (Admin panel -> top right)."
  echo "  Your data is stored in ./data and Redis in the 'redis_data' volume."
  echo
  $DC ps
}

# ---------------------------------- menu ------------------------------------

banner() {
  echo
  echo "================================"
  echo "   MovieFlix  Docker Installer"
  echo "================================"
}

main() {
  req_check

  [ "${1:-}" = "--yes" ] && [ "${2:-}" = "2" ] && { AUTOWIPE=1; } || AUTOWIPE=0

  banner
  echo "  Choose an installation mode:"
  echo "    1) Update only      — keep data + settings, fastest"
  echo "    2) Complete wipeout — FRESH installation (erases everything)"
  echo "    3) Quit"
  echo

  if [ "$AUTOWIPE" = "1" ]; then
    info "Auto-running complete wipeout (--yes 2)."
    do_wipeout
    exit 0
  fi

  read -rp "Select [1/2/3]: " choice
  case "${choice:-3}" in
    1) do_update ;;
    2) do_wipeout ;;
    3) echo "Bye."; exit 0 ;;
    *) die "Invalid choice." ;;
  esac
}

main "$@"