#!/usr/bin/env bash
# =============================================================================
#  MovieFlix Docker Installer — two modes, both via Docker Compose
#
#  1) UPDATE ONLY  — pull the latest code, rebuild the image, restart the app.
#                    Keeps ./data (database, thumbnails, uploads) and .env.
#
#  2) COMPLETE WIPEOUT — FRESH INSTALLATION. Stops and removes every container,
#                    deletes the database + all user data, wipes Redis, resets
#                    the repo to origin/main and rotates the JWT secrets.
#                    Your OTHER .env settings (media paths, URL, TMDB, SMTP)
#                    are PRESERVED and backed up. ANY local source changes are
#                    discarded. *** DESTRUCTIVE — type YES to confirm. ***
#
#  Run from the project root (where docker-compose.yml lives):
#      chmod +x install.sh && ./install.sh
# =============================================================================

set -euo pipefail

# ----------------------------- helpers --------------------------------------

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[info]${NC}  $*"; }
ok()    { echo -e "${GREEN}[ok]${NC}   $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*"; }
die()   { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

gen_secret() {
  # 48 hex chars (>= the 32 char minimum enforced by the app)
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 24
  else
    head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n'
  fi
}

# --------------------------- prerequisite checks ----------------------------

req_check() {
  command -v docker >/dev/null 2>&1 || die "Docker is not installed or not in PATH."
  docker info >/dev/null 2>&1 || die "Docker daemon is not running (is the service started?)."

  if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
  elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
  else
    die "Docker Compose (v2) is not installed. Install the compose plugin, e.g.:\n  sudo apt install docker-compose-plugin"
  fi
  info "Using: $DC"

  command -v git >/dev/null 2>&1 || die "git is not installed."
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "Not a git repository. Run this script from the MovieFlix project root."
  [ -f docker-compose.yml ] || die "docker-compose.yml not found. Run this script from the MovieFlix project root."
}

swap_check() {
  # The Next.js production build needs ~3GB of ram+swap. On the low-RAM host,
  # building without a swapfile stalls the machine (see Dockerfile header).
  local ram_mb swap_mb total_gb
  ram_mb=$(awk '/MemTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 0)
  swap_mb=$(awk '/SwapTotal/{print int($2/1024)}' /proc/meminfo 2>/dev/null || echo 0)
  total_gb=$(( (ram_mb + swap_mb) / 1024 ))

  if [ "$total_gb" -lt 3 ]; then
    warn "Host has only ~${total_gb}GB of ram+swap (Ram: ${ram_mb}MB, Swap: ${swap_mb}MB)."
    warn "The Docker build may run out of memory and freeze the server."
    warn "Add a swapfile before proceeding, e.g.:"
    warn "  sudo fallocate -l 6G /swapfile && sudo chmod 600 /swapfile"
    warn "  sudo mkswap /swapfile && sudo swapon /swapfile"
    read -rp "Continue anyway? (y/N) " -n1 yn
    echo
    [ "$yn" = "y" ] || [ "$yn" = "Y" ] || die "Aborted. Free up ram/swap and try again."
  fi
}

# ----------------------------- .env handling --------------------------------

write_env_template() {
  # Regenerates .env from scratch (used by the WIPEOUT mode).
  local jwt_s jwt_r admin_p
  jwt_s=$(gen_secret)
  jwt_r=$(gen_secret)
  admin_p=$(gen_secret)
  cat > .env <<EOF
# ===========================================
# MovieFlix — generated by install.sh (${1:-mode})
# ===========================================

# JWT secrets — REQUIRED, at least 32 chars (auto-generated)
JWT_SECRET=${jwt_s}
JWT_REFRESH_SECRET=${jwt_r}

# Initial administrator (used only when the database has no administrator yet)
ADMIN_USERNAME=admin
ADMIN_INITIAL_PASSWORD=${admin_p}

# Public URL of the app (used in email links). Update to your real address.
# e.g. http://SERVER_IP:9000  or  https://movieflix.example.com
APP_PUBLIC_URL=http://localhost:9000

# PayMongo automated billing (use test keys first).
# Configure APP_PUBLIC_URL/api/billing/webhook/paymongo in PayMongo.
# The webhook secret below must be the signing secret (whsk_...), not that URL.
PAYMONGO_SECRET_KEY=
PAYMONGO_PUBLIC_KEY=
PAYMONGO_WEBHOOK_SECRET=

# TMDB metadata (optional). Free key: https://www.themoviedb.org/settings/api
TMDB_API_KEY=
TMDB_BASE_URL=https://api.themoviedb.org/3
TMDB_IMAGE_BASE_URL=https://image.tmdb.org/t/p/

# SMTP so emails actually deliver (welcome, password reset, broadcast…).
# Without this the app still runs, but no emails are sent.
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=MovieFlix <movieflix.support@gmail.com>

# Optional: restrict sessions to the same /24 subnet (0 = off, 1 = on)
SESSION_STRICT_SUBNET=0

# Host paths of your movie & series libraries (mapped into the container at
# /media/movies and /media/series). Set these to your real folders, e.g.:
#   MEDIA_MOVIES_HOST=/mnt/media/Media/MOVIES
#   MEDIA_SERIES_HOST=/mnt/media/Media/TV
# They live in .env on purpose: git pull / install.sh updates will NOT overwrite them.
MEDIA_MOVIES_HOST=/media/movies
MEDIA_SERIES_HOST=/media/series
EOF
  chmod 600 .env
}

ensure_env() {
  # UPDATE mode keeps the existing .env; only generates one if absent.
  if [ ! -f .env ]; then
    warn ".env not found — generating one with fresh secrets."
    write_env_template update
    warn "Edit .env to set APP_PUBLIC_URL, TMDB_API_KEY and SMTP_* before first launch."
  else
    ok "Reusing existing .env (secret JWT values are preserved)."
    if ! grep -q '^ADMIN_INITIAL_PASSWORD=' .env; then
      printf '\nADMIN_USERNAME=admin\nADMIN_INITIAL_PASSWORD=%s\n' "$(gen_secret)" >> .env
      chmod 600 .env
      ok "Generated the missing initial administrator credential."
    fi
  fi
  local paymongo_webhook_secret
  paymongo_webhook_secret=$(awk -F= '$1=="PAYMONGO_WEBHOOK_SECRET"{sub(/^[^=]*=/,""); print; exit}' .env)
  if [[ "$paymongo_webhook_secret" =~ ^https?:// ]]; then
    warn "PAYMONGO_WEBHOOK_SECRET contains a URL, so paid accounts cannot activate."
    warn "Replace it with the PayMongo webhook signing secret (whsk_...)."
  fi
}

env_value() {
  awk -F= -v key="$1" '$1==key{sub(/^[^=]*=/,""); print; exit}' .env
}

write_env_value_securely() {
  local key="$1" value="$2" tmp line found=0
  tmp=$(mktemp "${TMPDIR:-/tmp}/movieflix-env.XXXXXX") || return 1
  chmod 600 "$tmp"
  while IFS= read -r line || [ -n "$line" ]; do
    if [[ "$line" == "${key}="* ]]; then
      printf '%s=%s\n' "$key" "$value" >> "$tmp"
      found=1
    else
      printf '%s\n' "$line" >> "$tmp"
    fi
  done < .env
  [ "$found" = "1" ] || printf '\n%s=%s\n' "$key" "$value" >> "$tmp"
  cat "$tmp" > .env
  chmod 600 .env
  rm -f "$tmp"
}

provision_paymongo_webhook() {
  local secret_key public_key webhook_secret key_mode public_mode public_url webhook_url
  local curl_config response_file payload_file http_code webhook_record webhook_id webhook_status

  secret_key=$(env_value PAYMONGO_SECRET_KEY)
  public_key=$(env_value PAYMONGO_PUBLIC_KEY)
  webhook_secret=$(env_value PAYMONGO_WEBHOOK_SECRET)

  if [ -z "$secret_key" ] || [ -z "$public_key" ]; then
    info "PayMongo keys are not configured; automatic webhook setup skipped."
    return 0
  fi
  case "$secret_key" in sk_live_*) key_mode="live" ;; sk_test_*) key_mode="test" ;; *) warn "PAYMONGO_SECRET_KEY has an invalid format; webhook setup skipped."; return 0 ;; esac
  case "$public_key" in pk_live_*) public_mode="live" ;; pk_test_*) public_mode="test" ;; *) warn "PAYMONGO_PUBLIC_KEY has an invalid format; webhook setup skipped."; return 0 ;; esac
  if [ "$key_mode" != "$public_mode" ]; then
    warn "PayMongo secret/public keys use different modes; webhook setup skipped."
    return 0
  fi
  case "$webhook_secret" in whsk_*) ok "PayMongo webhook signing secret is already configured; keeping it unchanged."; return 0 ;; esac

  command -v curl >/dev/null 2>&1 || { warn "curl is unavailable; automatic PayMongo webhook setup skipped."; return 0; }
  command -v python3 >/dev/null 2>&1 || { warn "python3 is unavailable; automatic PayMongo webhook setup skipped."; return 0; }

  curl_config=$(mktemp "${TMPDIR:-/tmp}/movieflix-paymongo-curl.XXXXXX") || return 0
  response_file=$(mktemp "${TMPDIR:-/tmp}/movieflix-paymongo-response.XXXXXX") || { rm -f "$curl_config"; return 0; }
  payload_file=$(mktemp "${TMPDIR:-/tmp}/movieflix-paymongo-payload.XXXXXX") || { rm -f "$curl_config" "$response_file"; return 0; }
  chmod 600 "$curl_config" "$response_file" "$payload_file"
  printf 'user = "%s:"\nsilent\nshow-error\n' "$secret_key" > "$curl_config"

  info "Checking PayMongo for an existing MovieFlix webhook (${key_mode} mode)."
  http_code=$(curl --config "$curl_config" --request GET --url https://api.paymongo.com/v1/webhooks --output "$response_file" --write-out '%{http_code}' 2>/dev/null || true)
  if [ "$http_code" != "200" ]; then
    warn "PayMongo webhook lookup failed (HTTP ${http_code:-network error}); existing configuration was left unchanged."
    rm -f "$curl_config" "$response_file" "$payload_file"
    return 0
  fi

  webhook_record=$(python3 - "$response_file" "$key_mode" <<'PY'
import json, sys
try:
    payload = json.load(open(sys.argv[1], encoding="utf-8"))
    live = sys.argv[2] == "live"
    for item in payload.get("data", []):
        attrs = item.get("attributes", {})
        if attrs.get("livemode") == live and "/api/billing/webhook/paymongo" in attrs.get("url", ""):
            print("|".join((str(item.get("id", "")), str(attrs.get("secret_key", "")), str(attrs.get("status", "")), str(attrs.get("url", "")))))
            break
except Exception:
    pass
PY
  )

  if [ -n "$webhook_record" ]; then
    IFS='|' read -r webhook_id webhook_secret webhook_status webhook_url <<< "$webhook_record"
    if [ "$webhook_status" = "disabled" ] && [ -n "$webhook_id" ]; then
      http_code=$(curl --config "$curl_config" --request POST --url "https://api.paymongo.com/v1/webhooks/${webhook_id}/enable" --output "$response_file" --write-out '%{http_code}' 2>/dev/null || true)
      [ "$http_code" = "200" ] || warn "Existing PayMongo webhook could not be re-enabled (HTTP ${http_code:-network error})."
    fi
  else
    public_url=$(env_value APP_PUBLIC_URL)
    if [[ ! "$public_url" =~ ^https:// ]]; then
      warn "No existing webhook was found and APP_PUBLIC_URL is not a public HTTPS address; webhook setup skipped."
      rm -f "$curl_config" "$response_file" "$payload_file"
      return 0
    fi
    webhook_url="${public_url%/}/api/billing/webhook/paymongo"
    MOVIEFLIX_WEBHOOK_URL="$webhook_url" python3 - <<'PY' > "$payload_file"
import json, os
print(json.dumps({"data":{"attributes":{"url":os.environ["MOVIEFLIX_WEBHOOK_URL"],"events":["payment.paid","payment.failed"]}}}))
PY
    info "Creating the MovieFlix PayMongo webhook (${key_mode} mode)."
    http_code=$(curl --config "$curl_config" --request POST --url https://api.paymongo.com/v1/webhooks --header 'Content-Type: application/json' --data-binary "@$payload_file" --output "$response_file" --write-out '%{http_code}' 2>/dev/null || true)
    if [ "$http_code" != "200" ] && [ "$http_code" != "201" ]; then
      warn "PayMongo webhook creation failed (HTTP ${http_code:-network error}); no secret was written."
      rm -f "$curl_config" "$response_file" "$payload_file"
      return 0
    fi
    webhook_secret=$(python3 - "$response_file" <<'PY'
import json, sys
try: print(json.load(open(sys.argv[1], encoding="utf-8"))["data"]["attributes"]["secret_key"])
except Exception: pass
PY
    )
  fi

  if [[ "$webhook_secret" == whsk_* ]]; then
    if write_env_value_securely PAYMONGO_WEBHOOK_SECRET "$webhook_secret"; then
      ok "PayMongo webhook signing secret was installed securely in .env."
    else
      warn "The webhook exists, but its signing secret could not be written to .env."
    fi
  else
    warn "PayMongo did not return a valid webhook signing secret; .env was not changed."
  fi
  rm -f "$curl_config" "$response_file" "$payload_file"
  unset secret_key public_key webhook_secret
}

rotate_secrets_in_env() {
  # Rewrite ONLY the JWT secrets inside an existing .env, keeping every other
  # setting the user configured (media paths, APP_PUBLIC_URL, TMDB, SMTP, ...).
  # Falls back to a fresh template if the JWT lines are missing.
  local jwt_s jwt_r
  jwt_s=$(gen_secret)
  jwt_r=$(gen_secret)
  if grep -q '^JWT_SECRET=' .env && grep -q '^JWT_REFRESH_SECRET=' .env; then
    sed -i "s|^JWT_SECRET=.*|JWT_SECRET=${jwt_s}|" .env
    sed -i "s|^JWT_REFRESH_SECRET=.*|JWT_REFRESH_SECRET=${jwt_r}|" .env
    ok "Rotated JWT secrets — all other .env settings were preserved."
  else
    warn "Existing .env was missing the JWT lines — regenerating a fresh template."
    write_env_template wipeout
  fi
}

reset_env() {
  if [ -f .env ]; then
    local bak
    bak=".env.bak.$(date +%Y%m%d-%H%M%S)"
    cp .env "$bak" 2>/dev/null || true
    info "Backed up your current configuration to $bak"
    rotate_secrets_in_env
  else
    write_env_template wipeout
    ok "Generated a fresh .env with brand-new JWT secrets."
  fi
  warn "Edit .env now if you want: APP_PUBLIC_URL, TMDB_API_KEY, SMTP_*."
}

# Best-effort detection of the host's movie/series folders. Scans the usual
# media mount points (e.g. Home Assistant/media boxes put it under /mnt/media).
detect_media_dir() {
  # $1 = label: "movies" | "series"
  local base found pattern
  if [ "$1" = "movies" ]; then
    pattern='\( -iname movies -o -iname movie -o -iname films \)'
  else
    pattern='\( -iname series -o -iname tvshows -o -iname "tv shows" -o -iname shows \)'
  fi
  for base in /mnt/media/Media /mnt/media /mnt/Media /media /opt/media /srv/media /data/media /media/data /mnt/data/media; do
    [ -d "$base" ] || continue
    # shellcheck disable=SC2086
    found=$(find "$base" -maxdepth 4 -type d $pattern -print -quit 2>/dev/null) || true
    [ -n "$found" ] && { echo "$found"; return 0; }
  done
  return 1
}

tune_media_env() {
  # Point MEDIA_MOVIES_HOST / MEDIA_SERIES_HOST in .env at a real library when
  # they still hold the defaults (and a library is findable). Skips any value
  # the user has deliberately set to something other than the default.
  local kind cur value
  for kind in movies series; do
    cur=$(awk -F= -v k="MEDIA_${kind^^}_HOST" '$1==k{gsub(/[[:space:]]/,"",$2); print $2}' .env)
    case "$kind" in
      movies) [ "$cur" = "/media/movies" ] || [ -z "$cur" ] || continue ;;
      series) [ "$cur" = "/media/series" ] || [ -z "$cur" ] || continue ;;
    esac
    if value=$(detect_media_dir "$kind") && [ -n "$value" ] && [ "$value" != "$cur" ]; then
      if grep -q "MEDIA_${kind^^}_HOST" .env; then
        sed -i "s|^MEDIA_${kind^^}_HOST=.*|MEDIA_${kind^^}_HOST=$value|" .env
      else
        printf 'MEDIA_%s_HOST=%s\n' "${kind^^}" "$value" >> .env
      fi
      ok "Detected $kind library at $value -> MEDIA_${kind^^}_HOST set in .env."
      continue
    fi
    [ "${1:-}" = "quiet" ] || warn "No $kind library auto-detected. MEDIA_${kind^^}_HOST stays '$cur' — edit .env if needed."
  done
}

backup_live_database() {
  # Use SQLite's online backup API through the running app. This produces a
  # transactionally consistent copy even while WAL mode is active.
  [ -f ./data/database.sqlite ] || return 0
  mkdir -p ./data/backups
  local stamp backup
  stamp=$(date +%Y%m%d-%H%M%S)
  backup="./data/backups/database-before-update-${stamp}.sqlite"
  if $DC exec -T app node -e 'const D=require("better-sqlite3");const s=new D("./data/database.sqlite");s.backup(process.argv[1]).then(()=>{const b=new D(process.argv[1],{readonly:true});if(b.pragma("integrity_check",{simple:true})!=="ok")process.exit(2);b.close();s.close()})' "./data/backups/database-before-update-${stamp}.sqlite"; then
    ok "Created and verified database backup: $backup"
  else
    die "Database backup failed. The update was stopped before rebuilding or restarting anything."
  fi
}

# ----------------------------- install modes --------------------------------

do_update() {
  backup_live_database
  info "Pulling the latest code from origin/main (ff-only, safe)."
  git fetch origin
  git pull --ff-only origin main

  swap_check
  ensure_env
  tune_media_env
  provision_paymongo_webhook

  info "Stopping the running stack to free RAM for the build (runtime container limits are up to ~1.7GB)."
  $DC stop 2>/dev/null || true

  info "Rebuilding the Docker image (this takes a while on low-RAM hosts)."
  if ! $DC build; then
    warn "Build failed — restarting the previous stack so the service stays up."
    $DC up -d --force-recreate 2>/dev/null || true
    die "docker compose build failed. See the error above."
  fi

  info "Starting / restarting the stack."
  $DC up -d --force-recreate

  ok "Update complete. Containers:"
  $DC ps
}

do_wipeout() {
  local answer
  echo
  warn "You are about to do a COMPLETE WIPEOUT — FRESH INSTALLATION."
  warn "This will:"
  warn "  - Stop & remove the running containers and the Redis volume"
  warn "  - DELETE ./data (database.sqlite, all accounts, thumbnails, uploads)"
  warn "  - Discard any local source changes and reset the repo to origin/main"
  warn "  - Rotate the JWT secrets in .env (all your OTHER .env settings are kept, and a backup is written first)"
  echo
  read -rp "Type YES (uppercase) to continue: " answer
  [ "$answer" = "YES" ] || die "Wipeout cancelled."
  echo

  info "Stopping the stack and removing all containers/volumes."
  $DC down -v --remove-orphans 2>/dev/null || true

  info "Removing the app image (forces a clean rebuild)."
  docker rmi -f movieflix-app 2>/dev/null || true

  info "Deleting ./data (database + user data)."
  # The app container runs as root, so ./data contains root-owned files that a
  # plain `rm` as your user cannot remove ("Permission denied"). Delete through
  # a throwaway container instead — it runs as root and can wipe everything.
  if docker run --rm -v "$PWD":/work redis:7-alpine rm -rf /work/data 2>/dev/null; then
    ok "Data directory removed."
  elif docker run --rm -v "$PWD":/work alpine rm -rf /work/data 2>/dev/null; then
    ok "Data directory removed (using alpine)."
  else
    warn "Container-based removal failed. Falling back to sudo."
    sudo rm -rf ./data || die "Could not remove ./data: Permission denied. Fix manually, then re-run:\n  sudo chown -R \$(id -u):\$(id -g) ./data && sudo rm -rf ./data"
    ok "Data directory removed (via sudo)."
  fi

  info "Resetting the repository to origin/main (fresh source)."
  git fetch origin main
  git reset --hard origin/main
  git clean -fd --exclude=.env 2>/dev/null || true

  swap_check
  reset_env
  tune_media_env
  provision_paymongo_webhook

  info "Building the fresh image (this takes a while on low-RAM hosts)."
  $DC build

  info "Starting the stack."
  $DC up -d

  ok "Fresh install complete!"
  echo
  echo "  Admin username: admin"
  echo "  Initial password is stored in .env as ADMIN_INITIAL_PASSWORD."
  echo "  Your data is stored in ./data and Redis in the 'redis_data' volume."
  echo
  $DC ps
}

# ---------------------------------- menu ------------------------------------

remove_root_owned() {
  # ./data (and some dirs) are root-owned because the app container runs as
  # root. Delete them through a throwaway root container rather than a plain
  # `rm`, which fails with "Permission denied". Returns 0 on success.
  if docker run --rm -v "$PWD":/work redis:7-alpine rm -rf /work/"$1" 2>/dev/null; then
    return 0
  fi
  if docker run --rm -v "$PWD":/work alpine rm -rf /work/"$1" 2>/dev/null; then
    return 0
  fi
  return 1
}

do_uninstall() {
  local answer
  echo
  warn "You are about to COMPLETELY UNINSTALL MovieFlix from this host."
  warn "This will:"
  warn "  - Remove the app + redis containers and the docker network"
  warn "  - Remove the Redis volume"
  warn "  - Delete ./data (database, all accounts, thumbnails, uploads)"
  warn "  - Delete the .env file and every .env backup"
  warn "  - Remove the Docker images and build cache"
  echo
  read -rp "Type YES (uppercase) to confirm UNINSTALL: " answer
  [ "$answer" = "YES" ] || die "Uninstall cancelled."
  [ "$(echo "$answer")" = "YES" ] || die "Uninstall cancelled."
  echo

  info "Stopping the stack and removing containers/volumes."
  $DC down -v --remove-orphans 2>/dev/null || true

  info "Removing the Docker images."
  docker rmi -f movieflix-app 2>/dev/null || true
  docker images -q --filter=reference='movieflix-app:*' | xargs -r docker rmi -f 2>/dev/null || true

  info "Deleting ./data, .env and .env backups (root-owned files handled)."
  if remove_root_owned "data"; then
    ok "Removed ./data"
  else
    warn "Could not remove ./data through Docker. Trying sudo."
    sudo rm -rf ./data || warn "Failed to remove ./data — delete it manually with: sudo rm -rf ./data"
  fi
  rm -f .env .env.bak.* 2>/dev/null || true
  # Remove any stray empty bind-mount dirs Docker auto-created (media/series).
  rm -rf media mnt 2>/dev/null || true

  info "Pruning build cache and dangling images."
  docker builder prune -f 2>/dev/null || true

  ok "MovieFlix uninstalled. The project folder (this repo) still contains the"
  ok "source code; delete it with:  rm -rf \"$PWD\""
  echo "  (Optional) Free all unused Docker space:  docker system prune -a"
}

banner() {
  echo
  echo "================================"
  echo "   MovieFlix  Docker Installer"
  echo "================================"
}

main() {
  req_check

  [ "${1:-}" = "--yes" ] && [ "${2:-}" = "2" ] && { AUTOWIPE=1; } || AUTOWIPE=0

  banner
  echo "  Choose an installation mode:"
  echo "    1) Update only    — keep data + settings, fastest"
  echo "    2) Complete wipeout — FRESH installation (erases everything)"
  echo "    3) Uninstall      — remove containers, data, images from this host"
  echo "    4) Quit"
  echo

  if [ "$AUTOWIPE" = "1" ]; then
    info "Auto-running complete wipeout (--yes 2)."
    do_wipeout
    exit 0
  fi

  read -rp "Select [1/2/3/4]: " choice
  case "${choice:-4}" in
    1) do_update ;;
    2) do_wipeout ;;
    3) do_uninstall ;;
    4) echo "Bye."; exit 0 ;;
    *) die "Invalid choice." ;;
  esac
}

main "$@"
