import { randomUUID } from "crypto";
import { and, eq, gt, inArray, isNull, lt, or, sql } from "drizzle-orm";
import { db } from "@/db";
import { accounts,billingEvents,billingOrders,profiles,profileSettings,promoCodes,promoRedemptions,signupSessions,subscriptions,subscriptionPlans } from "@/db/schema";
import { verifyToken } from "@/lib/auth";
import { sendEmail } from "@/lib/email";
import { emailLayout, escapeHtml, greeting } from "@/lib/email-templates";
import { getSignupAccount } from "@/lib/registration";
import { paymentProvider } from "./provider";
import { pesosToMinor } from "./money";

export type BillingCustomer={account:typeof accounts.$inferSelect;signupSessionId:string|null};
export async function resolveCustomer(request:Request,signupToken?:string):Promise<BillingCustomer|null>{
 if(signupToken){const signup=await getSignupAccount(signupToken);if(signup)return{account:signup.account,signupSessionId:signup.session.id}}
 const cookie=request.headers.get("cookie")||"";const token=cookie.match(/(?:^|;\s*)access_token=([^;]+)/)?.[1];const payload=token?await verifyToken(decodeURIComponent(token)):null;if(!payload?.accountId||payload.accountId==="admin")return null;
 const [account]=await db.select().from(accounts).where(eq(accounts.id,payload.accountId)).limit(1);return account?{account,signupSessionId:null}:null;
}
export async function releaseExpiredReservations(){
 const now=new Date().toISOString();const expired=await db.select().from(billingOrders).where(and(eq(billingOrders.promoReserved,true),inArray(billingOrders.status,["CREATED","PENDING"]),lt(billingOrders.expiresAt,now)));
 for(const order of expired)db.transaction(tx=>{tx.update(billingOrders).set({status:"EXPIRED",promoReserved:false,updatedAt:now}).where(and(eq(billingOrders.id,order.id),eq(billingOrders.promoReserved,true))).run();if(order.promoId)tx.update(promoCodes).set({reservedUses:sql`max(0, ${promoCodes.reservedUses} - 1)`}).where(eq(promoCodes.id,order.promoId)).run()});
}
export async function quote(customer:BillingCustomer,planId:string,rawCode?:string){
 await releaseExpiredReservations();const [plan]=await db.select().from(subscriptionPlans).where(and(eq(subscriptionPlans.id,planId),eq(subscriptionPlans.isActive,true))).limit(1);if(!plan)throw new Error("Selected plan is unavailable");
 const original=pesosToMinor(plan.price);const planDiscount=plan.discountAmount>0&&(!plan.discountUntil||Date.parse(plan.discountUntil)>=Date.now())?pesosToMinor(plan.discountAmount):0;
 let promo:typeof promoCodes.$inferSelect|null=null,promoDiscount=0;const code=rawCode?.trim().toUpperCase();
 if(code){[promo]=await db.select().from(promoCodes).where(eq(promoCodes.code,code)).limit(1);const now=Date.now();if(!promo||!promo.isActive||(promo.startsAt&&Date.parse(promo.startsAt)>now)||(promo.expiresAt&&Date.parse(promo.expiresAt)<now)||(promo.forcedPlanId&&promo.forcedPlanId!==plan.id)||(promo.maxUses!=null&&promo.uses+promo.reservedUses>=promo.maxUses)||(promo.minimumPurchaseMinor>original-planDiscount))throw new Error("Promo code is invalid or not eligible for this plan");
  if(promo.newUsersOnly&&customer.account.registrationStatus!=="pending")throw new Error("This code is available only to new accounts");if(promo.birthdayMonthOnly&&(!customer.account.dateOfBirth||new Date(`${customer.account.dateOfBirth}T00:00:00`).getMonth()!==new Date().getMonth()))throw new Error("This code is available only during your birth month");
  const [{count}]=await db.select({count:sql<number>`count(*)`}).from(promoRedemptions).where(and(eq(promoRedemptions.promoId,promo.id),eq(promoRedemptions.accountId,customer.account.id)));if(count>=promo.perAccountLimit)throw new Error("This promo code has reached your account usage limit");
  promoDiscount=promo.discountType==="percent"?Math.round((original-planDiscount)*promo.percentOff/100):pesosToMinor(promo.discountAmount);if(promo.maximumDiscountMinor!=null)promoDiscount=Math.min(promoDiscount,promo.maximumDiscountMinor);
 }
 const discount=Math.min(original,planDiscount+promoDiscount),finalAmount=original-discount;return{plan,promo,originalAmountMinor:original,discountAmountMinor:discount,finalAmountMinor:finalAmount,currency:"PHP" as const};
}
export async function createOrder(request:Request,input:{planId:string;promoCode?:string;signupToken?:string}){
 const customer=await resolveCustomer(request,input.signupToken);if(!customer)throw new Error("Authentication required");const q=await quote(customer,input.planId,input.promoCode);const id=randomUUID(),now=new Date().toISOString(),expiresAt=new Date(Date.now()+30*60*1000).toISOString();
 const [pending]=await db.select().from(billingOrders).where(and(eq(billingOrders.accountId,customer.account.id),inArray(billingOrders.status,["CREATED","PENDING"]),gt(billingOrders.expiresAt,now))).limit(1);
 if(pending)return{id:pending.id,status:pending.status,qrImage:pending.qrImage,expiresAt:pending.expiresAt,amountMinor:pending.finalAmountMinor};
 db.transaction(tx=>{if(q.promo){const reserved=tx.update(promoCodes).set({reservedUses:sql`${promoCodes.reservedUses} + 1`}).where(and(eq(promoCodes.id,q.promo.id),eq(promoCodes.isActive,true),or(isNull(promoCodes.maxUses),lt(sql`${promoCodes.uses}+${promoCodes.reservedUses}`,q.promo.maxUses!)))).run();if(reserved.changes!==1)throw new Error("Promotion is no longer available");}tx.insert(billingOrders).values({id,accountId:customer.account.id,planId:q.plan.id,planNameSnapshot:q.plan.name,planDurationHoursSnapshot:q.plan.durationHours,planLifetimeSnapshot:q.plan.isLifetime,originalAmountMinor:q.originalAmountMinor,discountAmountMinor:q.discountAmountMinor,finalAmountMinor:q.finalAmountMinor,promoId:q.promo?.id||null,promoCodeSnapshot:q.promo?.code||null,promoDiscountTypeSnapshot:q.promo?.discountType||null,promoDiscountValueSnapshot:q.promo?q.promo.discountType==="percent"?q.promo.percentOff:pesosToMinor(q.promo.discountAmount):null,promoBonusHoursSnapshot:q.promo?.bonusHours||0,promoReserved:Boolean(q.promo),provider:q.finalAmountMinor===0?"internal":"paymongo",status:q.finalAmountMinor===0?"PROCESSING":"CREATED",expiresAt,createdAt:now,updatedAt:now}).run()});
 if(q.finalAmountMinor===0){await fulfillOrder({orderId:id,providerEventId:`internal:${id}`,eventType:"internal.free",providerPaymentId:null,amountMinor:0,currency:"PHP"});return{id,status:"PAID",qrImage:null,expiresAt:null,amountMinor:0}}
 if(q.finalAmountMinor<100){await failOrderCreation(id,"PayMongo QR Ph requires at least ₱1.00");throw new Error("Final payment must be at least ₱1.00")}
 try{const p=await paymentProvider.createPayment({orderId:id,amountMinor:q.finalAmountMinor,description:`MovieFlix ${q.plan.name}`});await db.update(billingOrders).set({providerIntentId:p.intentId,providerPaymentMethodId:p.paymentMethodId,qrImage:p.qrImage,status:"PENDING",expiresAt:p.expiresAt,updatedAt:new Date().toISOString()}).where(eq(billingOrders.id,id));return{id,status:"PENDING",qrImage:p.qrImage,expiresAt:p.expiresAt,amountMinor:q.finalAmountMinor}}catch(e){await failOrderCreation(id,e instanceof Error?e.message:"Provider error");throw e}
}
async function failOrderCreation(id:string,error:string){const [order]=await db.select().from(billingOrders).where(eq(billingOrders.id,id)).limit(1);db.transaction(tx=>{tx.update(billingOrders).set({status:"FAILED",promoReserved:false,updatedAt:new Date().toISOString()}).where(eq(billingOrders.id,id)).run();if(order?.promoId&&order.promoReserved)tx.update(promoCodes).set({reservedUses:sql`max(0,${promoCodes.reservedUses}-1)`}).where(eq(promoCodes.id,order.promoId)).run()});console.error("billing.order_create_failed",{orderId:id,error})}
export async function fulfillOrder(input:{orderId?:string;providerIntentId?:string;providerEventId:string;eventType:string;providerPaymentId:string|null;amountMinor:number;currency:string}){
 const [order]=input.orderId?await db.select().from(billingOrders).where(eq(billingOrders.id,input.orderId)).limit(1):await db.select().from(billingOrders).where(eq(billingOrders.providerIntentId,input.providerIntentId!)).limit(1);
 if(!order)throw new Error("Billing order not found");if(order.finalAmountMinor!==input.amountMinor||order.currency!==input.currency)throw new Error("Provider amount or currency mismatch");const now=new Date().toISOString();
 const fulfilled=db.transaction(tx=>{const inserted=tx.insert(billingEvents).values({id:randomUUID(),provider:order.provider,providerEventId:input.providerEventId,eventType:input.eventType,orderId:order.id,status:"PROCESSING",receivedAt:now}).onConflictDoNothing().run();if(inserted.changes!==1)return false;const current=tx.select().from(billingOrders).where(eq(billingOrders.id,order.id)).get();if(!current||current.status==="PAID"){tx.update(billingEvents).set({status:"DUPLICATE",processedAt:now}).where(eq(billingEvents.providerEventId,input.providerEventId)).run();return false}
  const account=tx.select().from(accounts).where(eq(accounts.id,order.accountId)).get();if(!account)throw new Error("Account not found");const base=account.expiresAt&&Date.parse(account.expiresAt)>Date.now()?Date.parse(account.expiresAt):Date.now();const hours=(order.planDurationHoursSnapshot||0)+order.promoBonusHoursSnapshot;const entitlementEnd=order.planLifetimeSnapshot?null:new Date(base+hours*3600000).toISOString();const subscription=tx.select().from(subscriptions).where(eq(subscriptions.accountId,account.id)).get();const sid=subscription?.id||randomUUID();tx.insert(subscriptions).values({id:sid,accountId:account.id,planId:order.planId,status:"ACTIVE",currentPeriodStart:now,currentPeriodEnd:entitlementEnd,isLifetime:order.planLifetimeSnapshot,autoRenew:false,cancelAtPeriodEnd:false,provider:order.provider,createdAt:subscription?.createdAt||now,updatedAt:now}).onConflictDoUpdate({target:subscriptions.accountId,set:{planId:order.planId,status:"ACTIVE",currentPeriodStart:now,currentPeriodEnd:entitlementEnd,isLifetime:order.planLifetimeSnapshot,autoRenew:false,cancelAtPeriodEnd:false,provider:order.provider,updatedAt:now}}).run();tx.update(accounts).set({expiresAt:entitlementEnd,isLocked:false,registrationStatus:"active",durationHours:order.planDurationHoursSnapshot,updatedAt:now}).where(eq(accounts.id,account.id)).run();if(!tx.select().from(profiles).where(eq(profiles.accountId,account.id)).get()){const pid=randomUUID();tx.insert(profiles).values({id:pid,accountId:account.id,name:account.fullName||account.username,isMainProfile:true,createdAt:now,updatedAt:now}).run();tx.insert(profileSettings).values({id:randomUUID(),profileId:pid,createdAt:now,updatedAt:now}).run()}
  if(order.promoId){tx.insert(promoRedemptions).values({id:randomUUID(),promoId:order.promoId,accountId:account.id,orderId:order.id,redeemedAt:now}).run();tx.update(promoCodes).set({uses:sql`${promoCodes.uses}+1`,reservedUses:sql`max(0,${promoCodes.reservedUses}-1)`,updatedAt:now}).where(eq(promoCodes.id,order.promoId)).run()}
  tx.update(billingOrders).set({subscriptionId:sid,providerPaymentId:input.providerPaymentId,status:"PAID",paidAt:now,promoReserved:false,qrImage:null,entitlementStart:now,entitlementEnd,updatedAt:now}).where(eq(billingOrders.id,order.id)).run();tx.update(billingEvents).set({status:"PROCESSED",processedAt:now}).where(eq(billingEvents.providerEventId,input.providerEventId)).run();if(customerSignup(account.registrationStatus))tx.update(signupSessions).set({completedAt:now}).where(and(eq(signupSessions.accountId,account.id),isNull(signupSessions.completedAt))).run();return true});
 if(fulfilled){const [account]=await db.select().from(accounts).where(eq(accounts.id,order.accountId)).limit(1);if(account?.email)void sendEmail({to:account.email,subject:"MovieFlix payment confirmed",html:emailLayout({title:"Your membership is active",bodyHtml:`${greeting(escapeHtml(account.fullName||account.username))}<p>PayMongo confirmed your payment for <strong>${escapeHtml(order.planNameSnapshot)}</strong>. Your MovieFlix access is ready.</p>`})})}
 return order.id;
}
function customerSignup(status:string){return status==="pending"||status==="awaiting_payment_approval"}
