import { asc, eq, sql } from "drizzle-orm"; import { v4 as uuidv4 } from "uuid";
import { db } from "@/db"; import { promoCodes, subscriptionPlans } from "@/db/schema"; import { verifyToken } from "@/lib/auth"; import { successResponse,errorResponse } from "@/lib/api-response";
async function admin(r:Request){const cookie=r.headers.get("cookie")||"";const token=cookie.match(/(?:^|; )admin_token=([^;]+)/)?.[1];return token?verifyToken(decodeURIComponent(token)):null;}
export async function GET(r:Request){const a=await admin(r);if(!a?.isAdmin)return errorResponse("Admin access required",403);return successResponse({plans:await db.select().from(subscriptionPlans).orderBy(asc(subscriptionPlans.sortOrder))});}
export async function POST(r:Request){try{const a=await admin(r);if(!a?.isAdmin)return errorResponse("Admin access required",403);const b=await r.json();const name=String(b.name||"").trim(),price=Number(b.price),discountAmount=Number(b.discountAmount||0),durationHours=Number(b.durationHours||0),isLifetime=Boolean(b.isLifetime),isActive=b.isActive!==false;
if(!name||name.length>60||!Number.isFinite(price)||price<0||!Number.isFinite(discountAmount)||discountAmount<0||discountAmount>price||(!isLifetime&&(!Number.isInteger(durationHours)||durationHours<1)))return errorResponse("Enter a valid plan name, duration, price, and discount",400);
if(isActive){const [{count}]=await db.select({count:sql<number>`count(*)`}).from(subscriptionPlans).where(eq(subscriptionPlans.isActive,true));if(count>=4)return errorResponse("A maximum of four active plans is allowed",400);}
const now=new Date().toISOString(),id=uuidv4();await db.insert(subscriptionPlans).values({id,name,price,discountAmount,durationHours:isLifetime?null:durationHours,isLifetime,discountUntil:b.discountUntil||null,isActive,sortOrder:Number(b.sortOrder||0),createdAt:now,updatedAt:now});return successResponse({id},201);
}catch(e){console.error(e);return errorResponse("Unable to save plan",500)}}
export async function PATCH(r:Request){try{const a=await admin(r);if(!a?.isAdmin)return errorResponse("Admin access required",403);const b=await r.json();const [p]=await db.select().from(subscriptionPlans).where(eq(subscriptionPlans.id,String(b.id))).limit(1);if(!p)return errorResponse("Plan not found",404);const name=String(b.name??p.name).trim(),price=Number(b.price??p.price),discountAmount=Number(b.discountAmount??p.discountAmount),isLifetime=b.isLifetime??p.isLifetime,durationHours=Number(b.durationHours??p.durationHours??0),isActive=b.isActive??p.isActive;if(!name||price<0||discountAmount<0||discountAmount>price||(!isLifetime&&durationHours<1))return errorResponse("Invalid plan values",400);await db.update(subscriptionPlans).set({name,price,discountAmount,isLifetime,durationHours:isLifetime?null:durationHours,discountUntil:b.discountUntil===undefined?p.discountUntil:(b.discountUntil||null),isActive,sortOrder:Number(b.sortOrder??p.sortOrder),updatedAt:new Date().toISOString()}).where(eq(subscriptionPlans.id,p.id));return successResponse({message:"Plan updated"});}catch(e){console.error(e);return errorResponse("Unable to update plan",500)}}
export async function DELETE(r:Request){const a=await admin(r);if(!a?.isAdmin)return errorResponse("Admin access required",403);const id=new URL(r.url).searchParams.get("id");if(!id)return errorResponse("Plan ID required",400);db.transaction(tx=>{tx.update(promoCodes).set({forcedPlanId:null,updatedAt:new Date().toISOString()}).where(eq(promoCodes.forcedPlanId,id)).run();tx.delete(subscriptionPlans).where(eq(subscriptionPlans.id,id)).run()});return successResponse({message:"Plan deleted"});}
