"use client";
import { Suspense, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { CheckCircle, Eye, EyeOff, KeyRound, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

function Form() {
  const params = useSearchParams(); const router = useRouter(); const token = params.get("token") || ""; const initialIdentifier = params.get("identifier") || "";
  const [identifier, setIdentifier] = useState(initialIdentifier); const [verificationCode, setVerificationCode] = useState(""); const [password, setPassword] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); const [loading, setLoading] = useState(false); const [done, setDone] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (password !== confirm) return setError("Passwords do not match"); setLoading(true); setError(""); try { const response = await fetch("/api/admin/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, identifier, verificationCode, newPassword: password }) }); const data = await response.json(); if (!data.success) throw new Error(data.error); setDone(true); setTimeout(() => router.replace("/admin-panel/login"), 1400); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not reset password"); } finally { setLoading(false); } }
  if (done) return <div className="text-center"><CheckCircle className="mx-auto h-12 w-12 text-emerald-300"/><h1 className="mt-4 text-2xl font-black">Password updated</h1><p className="mt-2 text-sm text-slate-400">Redirecting to administrator sign in…</p></div>;
  return <><h1 className="text-center text-2xl font-black">Set a new admin password</h1><p className="mt-2 text-center text-sm text-slate-400">{token ? "This secure email link authorizes your reset." : "Enter the emailed six-digit code, or paste one of the ten one-time recovery codes saved when two-step verification was enabled."}</p><form onSubmit={submit} className="mt-7 space-y-4">{!token && <><div><Label htmlFor="identifier">Administrator username or email</Label><Input id="identifier" value={identifier} onChange={(event) => setIdentifier(event.target.value.toLowerCase())} autoComplete="username" autoCapitalize="none" autoCorrect="off" spellCheck={false} className="mt-1.5 h-12 border-white/15 bg-white/5" required/></div><div><Label htmlFor="code">6-digit email code or one-time recovery code</Label><Input id="code" value={verificationCode} onChange={(event) => setVerificationCode(event.target.value.toUpperCase())} autoComplete="one-time-code" className="mt-1.5 h-12 border-white/15 bg-white/5 font-mono tracking-wider" required/></div></>}<div><Label htmlFor="password">New password</Label><div className="relative"><Input id="password" type={show ? "text" : "password"} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="new-password" autoCapitalize="none" autoCorrect="off" spellCheck={false} minLength={8} required className="mt-1.5 h-12 border-white/15 bg-white/5 pr-12"/><button type="button" onClick={() => setShow((value) => !value)} aria-label={show ? "Hide password" : "Show password"} className="absolute inset-y-0 right-0 mt-1.5 flex w-12 items-center justify-center text-slate-400">{show ? <EyeOff className="h-5 w-5"/> : <Eye className="h-5 w-5"/>}</button></div><p className="mt-1 text-xs text-slate-500">Use at least 8 characters.</p></div><div><Label htmlFor="confirm">Confirm new password</Label><Input id="confirm" type={show ? "text" : "password"} value={confirm} onChange={(event) => setConfirm(event.target.value)} autoComplete="new-password" autoCapitalize="none" autoCorrect="off" spellCheck={false} minLength={8} required className="mt-1.5 h-12 border-white/15 bg-white/5"/></div>{error && <p role="alert" className="rounded-xl border border-red-400/30 bg-red-950/40 p-3 text-sm text-red-200">{error}</p>}<Button disabled={loading || password.length < 8 || password !== confirm} className="btn-brand h-12 w-full">{loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin"/> : <KeyRound className="mr-2 h-4 w-4"/>}Reset administrator password</Button></form><Link href="/admin-panel/login" className="mt-4 block min-h-11 py-3 text-center text-sm text-cyan-300 hover:underline">Return to admin sign in</Link></>;
}
export default function AdminResetPasswordPage() { return <main className="cinematic-bg flex min-h-screen items-center justify-center px-4 py-10 text-white"><section className="w-full max-w-md rounded-3xl border border-cyan-300/20 bg-[#0b1629]/95 p-6 shadow-2xl sm:p-9"><Suspense fallback={<Loader2 className="mx-auto h-8 w-8 animate-spin text-cyan-300"/>}><Form/></Suspense></section></main>; }
